config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :situations
  resources :call_finishes
  resources :call_services
  resources :services
  resources :components
  resources :customers

  resource :confirmation, only: [:show]

  root 'home#index'

end

app/models/service.rb
class Service < ActiveRecord::Base

	validates_presence_of :name

	validates_length_of :name, allow_blank: false
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<% if @service.errors.any? %>
<div id="error_explanation">
  <%= t 'general.form_error'%>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <p class="panel-title">Todos os campos são obrigatórios</p>
  </div>
  <div class="panel-body">
    <%= form_for(@service) do |f| %>

    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= error_tag @service, :name %>
    </div>
    <div class="form-group">
      <%= f.submit :class => "btn btn-info" %>
      <%= link_to t('links.back'), services_path, class: 'btn btn-default' %>
    </div>

    <% end %>
  </div>
</div>

app/views/services/edit.html.erb
<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Lista de Serviços', root_path %></li>
  <li class="active"><b>Editar Serviço</b></li>
</ol>

<h2><%= t '.title' %></h2>

<%= render 'form' %>

<!--<%= link_to 'Show', @service %> |
<%= link_to t('links.back'), services_path %>-->

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li class="active"><b>Lista de Serviços</b></li>
</ol>

<h2><%= t '.title' %></h2>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="title-table">Name</th>
        <th class="title-table">Ação</th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |service| %>
      <tr>
        <td class="title-body"><%= service.name %></td>
        <td>
          <%= link_to ' Edit', edit_service_path(service), class: 'btn btn-success glyphicon glyphicon-edit' %>
          <%= link_to ' Destroy', service, class: 'btn btn-danger glyphicon glyphicon-remove', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to ' New Service', new_service_path, class: 'btn btn-info glyphicon glyphicon-ok' %>

app/views/services/new.html.erb
<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Lista de Serviços', root_path %></li>
  <li class="active"><b>Criar Serviço</b></li>
</ol>

<h2><%= t '.title' %></h2>

<%= render 'form' %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>