config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :situations
  resources :call_finishes
  resources :call_services
  resources :services
  resources :components
  resources :customers

  resource :confirmation, only: [:show]

  root 'home#index'

end

app/models/situation.rb
class Situation < ActiveRecord::Base
end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  # GET /situations
  # GET /situations.json
  def index
    @situations = Situation.all
  end

  # GET /situations/1
  # GET /situations/1.json
  def show
  end

  # GET /situations/new
  def new
    @situation = Situation.new
  end

  # GET /situations/1/edit
  def edit
  end

  # POST /situations
  # POST /situations.json
  def create
    @situation = Situation.new(situation_params)

    respond_to do |format|
      if @situation.save
        format.html { redirect_to @situation, notice: 'Situation was successfully created.' }
        format.json { render :show, status: :created, location: @situation }
      else
        format.html { render :new }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /situations/1
  # PATCH/PUT /situations/1.json
  def update
    respond_to do |format|
      if @situation.update(situation_params)
        format.html { redirect_to @situation, notice: 'Situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @situation }
      else
        format.html { render :edit }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /situations/1
  # DELETE /situations/1.json
  def destroy
    @situation.destroy
    respond_to do |format|
      format.html { redirect_to situations_url, notice: 'Situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situation
      @situation = Situation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def situation_params
      params.require(:situation).permit(:name)
    end
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/views/situations/_form.html.erb
<% if @situation.errors.any? %>
<div id="error_explanation">
  <%= t 'general.form_error'%>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <p class="panel-title">Todos os campos são obrigatórios</p>
  </div>
  <div class="panel-body">

    <%= form_for(@situation) do |f| %>
      <div class="form-group">
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= error_tag @situation, :name %>
      </div>
      <div class="form-group">
        <%= f.submit :class => "btn btn-info" %>
        <%= link_to 'Back', situations_path, class: 'btn btn-default' %>
      </div>
    <% end %>

  </div>
</div>

app/views/situations/edit.html.erb
<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Lista de Situações', situations_path %></li>
  <li class="active"><b>Editar Situação</b></li>
</ol>

<h2><%= t '.title' %></h2>

<%= render 'form' %>

<!--<%= link_to 'Show', @situation %> |
<%= link_to 'Back', situations_path %>-->

app/views/situations/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li class="active"><b>Lista de Situações</b></li>
</ol>

<h2><%= t '.title' %></h2>

<div class="table-responsive">
  <table class="table table-bordered">
  <thead>
    <tr>
      <th class="title-table">Nome</th>
      <th class="title-table">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @situations.each do |situation| %>
      <tr>
        <td class="title-body"><%= situation.name %></td>
        <td>
          <%= link_to ' Edit', edit_situation_path(situation), class: 'btn btn-success glyphicon glyphicon-edit' %>
          <%= link_to ' Destroy', situation, class: 'btn btn-danger glyphicon glyphicon-remove', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to ' New Situation', new_situation_path, class: 'btn btn-info glyphicon glyphicon-ok' %>

app/views/situations/new.html.erb
<ol class="breadcrumb bc-3">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Lista de Situações', situations_path %></li>
  <li class="active"><b>Criar Situação</b></li>
</ol>

<h2><%= t '.title' %></h2>

<%= render 'form' %>

app/views/situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @situation.name %>
</p>

<%= link_to 'Edit', edit_situation_path(@situation) %> |
<%= link_to 'Back', situations_path %>