config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :situations
  resources :call_finishes
  resources :call_services
  resources :services
  resources :components
  resources :customers

  resource :confirmation, only: [:show]

  root 'home#index'

end

app/views/layouts/_navbar_user.html.erb
<li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home' %></li>
<li><%= link_to ' Serviços', services_path, class: 'glyphicon glyphicon-cog' %></li>
<li><%= link_to ' Componentes', components_path, class: 'glyphicon glyphicon-wrench' %></li>
<li><%= link_to ' Situações', situations_path, class: 'glyphicon glyphicon-list-alt' %></li>
<li><%= link_to ' Abrir Chamado', new_call_service_path, class: 'glyphicon glyphicon-phone-alt' %></li>
<!--<li><%= link_to ' Fechar Chamado', new_call_finish_path %></li>-->

app/views/layouts/_navbar_visitor.html.erb
<li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home' %></li>
<li><%= link_to ' Abrir Chamado', new_call_service_path, class: 'glyphicon glyphicon-phone-alt' %></li>
<!--<li><%= link_to ' Fechar Chamado', new_call_finish_path %></li>-->

app/views/layouts/_navigation.html.erb
<ul class="dropdown-menu">
  <% if user_signed_in? %>
      <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Minha Conta", edit_user_registration_path %></li>
  <% else %>
      <li><%= link_to "Entrar", new_user_session_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Criar Conta", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Callmycustomer</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Callmycustomer and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to ' Callmycustomer', root_path, class: 'navbar-brand glyphicon glyphicon-copyright-mark'%>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Minha Conta <span class="caret"></span></a>
						<%= render 'layouts/navigation' %>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 sidebar">
					<ul class="nav nav-sidebar">
						<% if user_signed_in? %>
							<%= render 'layouts/navbar_user' %>
						<% else %>
							<%= render 'layouts/navbar_visitor' %>
						<% end %>
					</ul>
			</div>
			<div class="col-md-10 col-md-offset-2 main">
				<% if notice.present? %>
		      <div class="alert alert-success" role="alert"><%= notice %></div>
		    <% end %>
		    <% if alert.present? %>
		      <div class="alert alert-danger" role="alert"><%= alert %></div>
		    <% end %>

				<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>